//! L5 nightly sweeps (VERIFICATION.md §2, §3.6): the full oracle set in `fixtures-full/`, regenerated by the nightly
//! job in the pinned image and never committed, read at run time. A missing file fails the sweep, never skips it.

#![allow(clippy::unwrap_used)] // test-crate helpers outside #[test] fns (unwrap is denied in library code)

use phasekit_core::{DataSet, Registry};
use phasekit_verify::eos::EosCheck;
use phasekit_verify::flash::FlashCheck;
use phasekit_verify::saturation::SaturationCheck;
use phasekit_verify::term::{self, TermCheck};
use phasekit_verify::{Cell, Fixture};

/// The full set's root, fixed at compile time (clippy bans run-time environment reads, D17).
const FULL: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures-full/coolprop-8.0.0");

/// fastchebpure's files of every fluid with a superancillary, from `cargo xtask fetch-fastchebpure --all` (PLAN.md M6.4).
const FASTCHEBPURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures-full/mp/fastchebpure-2026.06.02-v2");

/// A file of the full set; the error names the path.
#[allow(clippy::disallowed_methods, reason = "the nightly sweep reads the full set, too big to compile in (§3.6)")]
fn read(path: &str) -> String {
    std::fs::read_to_string(path).map_err(|e| format!("{path}: {e} (cargo xtask oracle --tier full)")).unwrap()
}

/// Oracle: CoolProp 8.0.0, fixtures-full/coolprop-8.0.0/term/<Fluid>.csv (PLAN.md M3.6, the M3 exit gate's nightly
/// part; every fluid since M4.1; α⁰ to order 3 since M4.3): α^r and its 14 derivatives on the 64-point totals grid, against
/// the whole residual part compiled from the `Parity` record; class `Term`, scale `majorant::eos`.
#[test]
#[ignore = "nightly: reads the full term set (cargo xtask oracle --kind term --tier full)"]
fn alphar_totals_match_oracle_on_the_nightly_grid() {
    let registry = Registry::embedded().unwrap();
    let (mut check, mut fluids) = (TermCheck::default(), 0);
    for f in phasekit_data::FLUIDS {
        let record = phasekit_core::internal::record(registry, f.name).unwrap();
        let path = format!("{FULL}/term/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        let totals: Vec<usize> = (0..fixture.rows().len())
            .filter(|&row| fixture.rows()[row].cells.first() == Some(&Cell::Text("all")))
            .collect();
        let ideal: Vec<usize> = (0..fixture.rows().len())
            .filter(|&row| fixture.rows()[row].cells.first() == Some(&Cell::Text("ideal")))
            .collect();
        assert_eq!((totals.len(), ideal.len()), (64, 64), "{path}");
        let eos = term::residual_part(&record.eos);
        check.rows(&fixture, &totals, term::residual_model(&record, &eos).unwrap().eos(), &eos);
        let scale = term::IdealScale::new(&record).unwrap();
        check.ideal_rows(&fixture, &ideal, record.clone().compile().unwrap().eos(), &scale);
        fluids += 1;
    }
    assert_eq!((fluids, check.checked), (136, 136 * 64 * (15 + 10)));
    assert_eq!(check.report(20), None);
}

/// Oracle: CoolProp 8.0.0, fixtures-full/coolprop-8.0.0/eos/<Fluid>.csv (PLAN.md M5.1, the M5 exit gate's nightly part):
/// p, h, s, u, cv, cp, w, Z, (∂p/∂ρ)_T and (∂p/∂T)_ρ, and since M5.5 the 12 partials, c_p⁰ and the residual parts, at
/// 10,000 (T, ρ) per fluid, phase imposed, against the DT flash of
/// the `Parity` data; class `Prop` with the floors of VERIFICATION.md §5, or `Term` carried through the relation where a
/// relation cancels (M5.1: 584 entries at Z ≈ 1e-4, next to a spinodal or in deep metastable liquid need it).
#[test]
#[ignore = "nightly: reads the full eos set (cargo xtask oracle --kind eos --tier full)"]
fn eos_fixtures_match_oracle_on_the_nightly_grid() {
    let registry = Registry::from_embedded(DataSet::Parity).unwrap();
    let mut check = EosCheck::default();
    for f in phasekit_data::FLUIDS {
        let path = format!("{FULL}/eos/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        let rows: Vec<usize> = (0..fixture.rows().len()).collect();
        assert_eq!(rows.len(), 10_000, "{path}");
        let record = phasekit_core::internal::record(&registry, f.name).unwrap();
        let fluid = registry.get(f.name).unwrap();
        check.rows(&fixture, &rows, fluid, &record);
        check.partial_rows(&fixture, &rows, fluid, &record, false);
        check.partial_rows(&fixture, &rows, fluid, &record, true);
    }
    assert_eq!(check.checked, 136 * 10_000 * (10 + 12 + 4));
    assert_eq!(check.report(60), None);
}

/// Oracle: CoolProp 8.0.0, fixtures-full/coolprop-8.0.0/sat/<Fluid>.csv (PLAN.md M5.2, the M5 exit gate's nightly part):
/// the superancillary's p, ρ′ and ρ″ at 200 temperatures per fluid of the 130 with one, Θ = 1 − T/Tc log-spaced from
/// 1e-7 to the triple point, against `CP.SuperAncillary(json).eval_sat`; class `SaCoeff`.
#[test]
#[ignore = "nightly: reads the full sat set (cargo xtask oracle --kind sat --tier full)"]
fn superancillary_matches_oracle_on_the_nightly_grid() {
    let registry = Registry::from_embedded(DataSet::Parity).unwrap();
    let (mut failures, mut checked, mut fluids) = (Vec::new(), 0, 0);
    for f in phasekit_data::FLUIDS {
        let record = phasekit_core::internal::record(&registry, f.name).unwrap();
        let Some(curve) = record.superancillary_curve() else { continue };
        let path = format!("{FULL}/sat/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        assert_eq!(fixture.rows().len(), 600, "{path}: 200 sa rows, then 200 QT (M5.2a) and 200 PQ rows (M6.8)");
        let sa = |row: &usize| fixture.rows()[*row].cells.first() == Some(&Cell::Text("sa"));
        for row in (0..fixture.rows().len()).filter(sa) {
            let sat = curve.at_t(fixture.value(row, "T").unwrap()).unwrap();
            for (column, got) in [("p", sat.bubble.p), ("rhoL", sat.bubble.rho), ("rhoV", sat.dew.rho)] {
                checked += 1;
                if let Err(e) = fixture.check_scaled(row, column, got, fixture.value(row, column).unwrap().abs()) {
                    failures.push(format!("{e:?}"));
                }
            }
        }
        fluids += 1;
    }
    assert_eq!((fluids, checked), (130, 130 * 200 * 3));
    assert_eq!(failures.iter().take(20).collect::<Vec<_>>(), Vec::<&String>::new(), "{} failures", failures.len());
}

/// Oracle: CoolProp 8.0.0, fixtures-full/coolprop-8.0.0/flash/<Fluid>.csv (PLAN.md M5.3): DT read off 40 × 40 (p, T)
/// and 20 × 20 (T, Q) truth states of every fluid, against CoolProp's DT flash; as `dt_two_phase_matches_oracle`.
#[test]
#[ignore = "nightly: reads the full flash set (cargo xtask oracle --kind flash --tier full)"]
fn dt_flash_matches_oracle_on_the_nightly_grid() {
    let registry = Registry::from_embedded(DataSet::Parity).unwrap();
    let mut check = FlashCheck::default();
    for f in phasekit_data::FLUIDS {
        let path = format!("{FULL}/flash/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        let record = phasekit_core::internal::record(&registry, f.name).unwrap();
        check.dt_rows(&fixture, registry.get(f.name).unwrap(), &record);
    }
    assert_eq!(check.report(50), None);
    assert!(check.two_phase > 130 * 300, "{check:?}");
}

/// The same over every fluid with a superancillary, from the nightly's `cargo xtask fetch-fastchebpure --all`
/// (PLAN.md M6.4, the M6 exit gate's nightly part; 204 050 rows): the measured constants at most 0.39 and 0.38 (here
/// 1); Chlorine's last row unsplit (Θ = 2.45e-7, the file's ρ′ = ρ″ between rows with a 5 % split); PropyleneGlycol's
/// p and ρ″ from 213 K to 227.6028 K exempt (DIV-0016, 52 cells). A missing file fails the sweep, never skips it.
#[test]
#[ignore = "nightly: reads every fluid's fastchebpure file (cargo xtask fetch-fastchebpure --all)"]
fn superancillary_and_vle_match_every_dense_multiprecision_file() {
    let registry = Registry::from_embedded(DataSet::Parity).unwrap();
    let mut saturation = SaturationCheck::default();
    let mut fluids = 0;
    for f in phasekit_data::FLUIDS {
        let record = phasekit_core::internal::record(&registry, f.name).unwrap();
        if record.superancillary_curve().is_none() {
            continue;
        }
        let path = format!("{FASTCHEBPURE}/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        let fluid = record.clone().compile().unwrap();
        saturation.rows(&fixture, f.name, &record, fluid.eos());
        fluids += 1;
    }
    assert_eq!(fluids, 130);
    assert_eq!(saturation.report(20), None);
    assert_eq!((saturation.unsplit, saturation.exempt), (1, 52), "Chlorine's last row; DIV-0016");
    let [density, pressure] = saturation.conditioning;
    assert!(density <= 1.0 && pressure <= 1.0, "measured conditioning {density:.2}, {pressure:.2}");
}
