//! L5 nightly sweeps (VERIFICATION.md §2, §3.6): the full oracle set in `fixtures-full/`, regenerated by the nightly
//! job in the pinned image and never committed, read at run time. A missing file fails the sweep, never skips it.

#![allow(clippy::unwrap_used)] // test-crate helpers outside #[test] fns (unwrap is denied in library code)

use phasekit_core::Registry;
use phasekit_verify::term::{self, TermCheck};
use phasekit_verify::{Cell, Fixture};

/// The full set's root, fixed at compile time (clippy bans run-time environment reads, D17).
const FULL: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures-full/coolprop-8.0.0");

/// A file of the full set; the error names the path.
#[allow(clippy::disallowed_methods, reason = "the nightly sweep reads the full set, too big to compile in (§3.6)")]
fn read(path: &str) -> String {
    std::fs::read_to_string(path).map_err(|e| format!("{path}: {e} (cargo xtask oracle --tier full)")).unwrap()
}

/// Oracle: CoolProp 8.0.0, fixtures-full/coolprop-8.0.0/term/<Fluid>.csv (PLAN.md M3.6, the M3 exit gate's nightly
/// part): α^r and its 14 derivatives of every fluid without NonAnalytic terms on the 64-point totals grid, against
/// the whole residual part compiled from the `Parity` record; class `Term`, scale `majorant::eos`.
#[test]
#[ignore = "nightly: reads the full term set (cargo xtask oracle --kind term --tier full)"]
fn alphar_totals_match_oracle_on_the_nightly_grid() {
    let registry = Registry::embedded().unwrap();
    let (mut check, mut fluids) = (TermCheck::default(), 0);
    for f in phasekit_data::FLUIDS {
        let record = phasekit_core::internal::record(registry, f.name).unwrap();
        if !record.eos.non_analytic.is_empty() {
            continue;
        }
        let path = format!("{FULL}/term/{}.csv", f.name);
        let text = read(&path);
        let fixture = Fixture::parse(&path, &text).unwrap();
        let totals: Vec<usize> = (0..fixture.rows().len())
            .filter(|&row| fixture.rows()[row].cells.first() == Some(&Cell::Text("all")))
            .collect();
        assert_eq!(totals.len(), 64, "{path}");
        let eos = term::residual_part(&record.eos);
        check.rows(&fixture, &totals, term::residual_model(&record, &eos).unwrap().eos(), &eos);
        fluids += 1;
    }
    assert_eq!((fluids, check.checked), (134, 134 * 64 * 15));
    assert_eq!(check.report(20), None);
}
